name = "MetalSurfaceImpedance"
uuid = "d1286fa9-018f-4163-8b95-1473a4173f0d"
authors = ["Peter Simon <psimon0420@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
